<template>
  <v-app>
    <v-container
      class="spacing-playground container__maxWidth"
      :class="{'pa-15': $vuetify.breakpoint.smAndUp}"
    >
      <div class="elevation-10"> 
        <v-app-bar flat class="rounded-t-lg" style="height: 70px">
          <template>
            <v-tabs icons-and-text 
                    :align-with-title="$vuetify.breakpoint.smAndUp"  
                    :fixed-tabs="$vuetify.breakpoint.xsOnly" 
                    v-model="tab"
                    style="width: 80%">
              <v-tab href="#home"> 
                home
                <v-icon>mdi-home</v-icon> 
              </v-tab>
              <v-tab href="#film"> 
                film
                <v-icon>mdi-video-vintage</v-icon> 
              </v-tab>
              <v-tab href="#about"> 
                about
                <v-icon>mdi-account</v-icon> 
              </v-tab>
            </v-tabs>
            <div class="text-h5 text-inner-shadow"
                 v-if="$vuetify.breakpoint.smAndUp">♑︎♋︎❒︎❒︎♓︎⬧︎□︎■︎</div>
          </template>
        </v-app-bar>

        <v-main>
          <v-tabs-items v-model="tab">
            <v-tab-item value="film">
              <div class="text-center helpbox__container my-2">
                <a href="#" class="helpbox">
                  <v-icon class="text-h3 grey--text">mdi-help-box</v-icon>
                </a>
                <div class="helpbox__description">
                  <div class="text-h5">procedural poems</div> <v-divider></v-divider>
                  <div class="helpbox__paragraph"> 
                    i've settled on calling these 'procedural poems' -- poems, because i think they should be approached like poems, not like prose -- and procedural, because their visual components are procedurally generated by math in fragment shaders (using either OpenGL ES 3.0 via WebGL or MSL via Apple's Metal) 
                    <br /> <br />
                    these videos are also 'art about art'. they experiment on the potential of contemporary aesthetic (i.e., the experience of art) as it becomes irrevocably multimodal and multimedia. by multimodal, I mean the content of any one sense modality (vision, hearing, a sense of touch or texture, time, or space) relies on some or all of the others in the whole of the piece's metaphor-making. 
                    for example, the primacy of sound and sight are interplayed in my first two pieces. this is not unlike theater, only more general and seemingly limitless, since it breaks away from the physical stage, acting, and an expectation of linear narrative.
                    <br /> <br />
                    milking this theatricality (a la Michael Fried), i am aiming for these experiences to <i>involve you.</i> they are objectively made investigations into experience itself. they are meant to be meditated on, not unlike yantras or mandalas. 
                  </div>
                </div>
              </div>
              <div class="grid">
                <a href="#" class="grid__item" tabindex="1">
                  <v-img
                  class="fill-height"
                  src="./assets/sound.png">
                  </v-img> 
                </a>
                <GridItem title="the sound of becoming" link="https://youtu.be/MZFCyl8PQQo" 
                          description="dual piece of ‘the look of becoming.’ here, the video starts with the conceptual - a kettle displayed in gory, surgical, textural detail, whose realism and objecthood gets disrupted periodically by a nondescript, flowing emulsion. the sound contrasts this with a strictly connotative or otherwise ambiguous sense-based collage of field recordings periodically rising up from the stretched sound of a kettle heating water. this piece is something like an ode to the fine-grained richness of qualia beyond concepts " />

                <a href="#" class="grid__item" tabindex="2">
                  <v-img
                    class="fill-height"
                    src="./assets/look.png">
                  </v-img> 
                </a>

                <GridItem title="the look of becoming" link="https://youtu.be/z1r47rU_yA8"
                          description="dual piece of ‘the sound of becoming.’ here, the video is essentially non-conceptual — an uncontrolled, ever-morphing, ever-disappearing play of forms, whose senseless shifting is only disrupted by the cross-fading of textures roughly interpreted as the linear progression of the seasons. the sound, by contrast, is easily conceptually filtered, consisting of a collage of FM radio programs, advertisements, music, religious ceremonies, field recordings of nature, etc, though i choose to further the dilemma of conceptual vs non-conceptual experience by frequently splitting the left and right channels in order to directly compare various combinations of sounds, making conceptualization more difficult. 
                                      to further the contrast of sensible vs senseless, conceptual vs non-conceptual, narrative vs non-narrative ‘scene setting’, the sounds are roughly organized according to the connotations of the seasons. in fact, i decided to use the collage of sounds and seasons to approximately narrate the two year period of my life in which i recorded most of the sounds — the end of college, my past relationship, my first time traveling abroad, and my fruitless return. this was my regulative principle. since these sounds are so evocative for me, this piece is personally something like a memory palace" />
                
                
                <a href="#" class="grid__item" tabindex="3">
                  <v-img
                    class="fill-height"
                    src="./assets/out.png">
                  </v-img> 
                </a>
                <GridItem title="PhotoLibrary_private141473.zip" link="https://youtu.be/AZEjhexDr3I" 
                          description="a feeling of numinous dread, especially as it is construed as the uncomfortable realization of an in-principle, boundary limit to knowledge, whose finite troubadour conquest is cut short by eternal death. sounds are recorded in walls, in air ducts, on pipes, and under bridges in pittsburgh and in long island city" />
              </div>

              <div class="grid">
                <a href="#" class="grid__item" tabindex="4">
                  <v-img
                    class="fill-height"
                    src="./assets/lux.png">
                  </v-img> 
                </a>
                <GridItem link="https://vimeo.com/548509429" title="lux mundi" description="the airy light fades like a flag in the wind, changing like the constant rhythmic clacking of train tracks, recorded on an overpass over the long island railroad in long island city, and once more from my apartment window" />

                <a href="#" class="grid__item" tabindex="5">
                  <v-img
                    class="fill-height"
                    src="./assets/rolling.png">
                  </v-img> 
                </a>
                <GridItem title="rolling ground memory, a pile mooring" link="https://youtu.be/BUo2qh0CX8Q" 
                          description="‘wetness’ contrasted with ‘flow’. the primary watery figure refracts onto a town square like a hazy memory. the hermit thrush’s slowed down song fades into the rich aether and then the rumbling waterfall of pipes. partially inspired by Clyfford Still’s 1944-N No. 2" />
                
                <a href="#" class="grid__item" tabindex="6">
                  <v-img
                    class="fill-height"
                    src="./assets/torpor.png">
                  </v-img> 
                </a>
                <GridItem title="torpor of the great consent" link="https://youtu.be/Af4lLzKZvgY" description="the consent of what things mean - the enveloping fiction of the profane, the finite - the maya. the music piece referenced is 'songs my mother taught me' by charles ives" />
              </div>
            </v-tab-item>
            <v-tab-item value="home">
              <WebGL/>
            </v-tab-item>
            <v-tab-item value="about">
              <v-container fluid class="text-center mt-5">
                <v-row class="justify-center">
                  <v-col class="col-9">
                    <v-avatar size="225">
                      <v-img src="./assets/me.jpg" class="rounded-circle">
                      </v-img>
                    </v-avatar>
                  </v-col>
                </v-row>
                <v-row class="justify-center">
                  <v-col class="col-9 text-h4">
                    Garrison McMullen
                  </v-col>
                </v-row>
                <v-row class="justify-center mt-0">
                  <v-col class="col-9">
                    likes full stack, graphics, music, art, and armchair academics
                    <br /> based in NYC
                  </v-col>
                </v-row>
                <v-row class="my-7">
                  <div class="ml-auto">
                    <v-btn
                      href="https://www.youtube.com/channel/UCcZYyXLJ7yEH3lWm58RoKRA"
                      target="_blank"
                      class="white red--text"
                      elevation="2"
                    ><v-icon>mdi-youtube</v-icon></v-btn>
                  </div>
                  <div class="mx-5">
                    <v-btn
                      href="https://www.linkedin.com/in/garrisonmcmullen"
                      target="_blank"
                      class="white blue--text text--darken-3"
                      elevation="2"
                    ><v-icon>mdi-linkedin</v-icon></v-btn>
                  </div>
                  <div class="mr-auto">
                    <v-btn
                      href="https://www.paypal.com/paypalme/moodmusic"
                      target="_blank"
                      class="red"
                      elevation="2"
                    >donate &nbsp; <v-icon>mdi-heart-circle</v-icon></v-btn>
                  </div>
                </v-row>
              </v-container>
            </v-tab-item>
          </v-tabs-items>
        </v-main>
      </div>
    </v-container>
  </v-app>
</template>

<script>
import WebGL from './components/WebGL';
import GridItem from './components/GridItem';


export default {
  name: 'App',

  components: {
    WebGL,
    GridItem
  },

  data: () => ({
    tab: 'home',
  }),
};
</script>

<style>

.v-application .primary--text, 
.v-tabs-slider,
.v-tab
{
  color: #b1ccaa !important;
  caret-color: #b1ccaa !important;
}

a {
  text-decoration: none;
}

header { 
  height: 84px!important;
}

.v-toolbar__content {
  height: 70px!important;
}

.v-toolbar__title { 
  overflow: visible!important;
}

.container__maxWidth { 
  max-width: 950px!important;
}

.text-inner-shadow {
   margin-right: 21px;
   opacity: 30%;
   /* color: rgb(0,0,0,0.4); */
   color: #6c4d6f;
   text-shadow: 2px 2px 2px #3d313f;
}

.grid__item {
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid #3d313f;
  min-height: 200px;
  font-size: 5em;
  color: inherit;
  text-decoration: none;
}

.grid__item:focus, .grid__item:hover{ 
  opacity: 50%;
  transition: opacity 0.125s ease-in-out;
}

.grid__item:focus + .grid__description { 
  max-height: 100vh;
  transition: max-height 0.65s ease-in-out;
  transition-delay: 0.55s;
}

.helpbox { 
  opacity: 50%;
  text-decoration: none;
}

.helpbox:focus, .helpbox:hover, helpbox:focus-within { 
  opacity: 100%;
  transition: opacity 0.125s ease-in-out;
}

.helpbox__description { 
  max-height: 0;
  margin-left: 5%;
  margin-right: 5%;
  overflow: hidden;
  transition: max-height 0.4s ease-in;
}

/* .helpbox__container:focus-within > .helpbox__description {  */
/* .helpbox__description:hover, */
.helpbox:focus + .helpbox__description {
  max-height: 100rem;
  transition: max-height 0.65s ease-in-out;
  transition-delay: 0.55s;
}

.helpbox__paragraph { 
  margin-top: 1rem;
  margin-bottom: 1rem;
}

.grid__description {
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.4s ease-in;
}

.grid__description .container {
  padding: 2em;
}

@media screen and (min-width: 30em) {
  .grid {
    display: grid;
    grid-template-areas:
      "item item item"
      "desc desc desc";
    grid-template-columns: 33.33% 33.33% 33.33%;
  }

  .grid__description {
    grid-area: desc;
  }

  .grid__item:focus + .grid__description { 
    max-height: 100vh;
  }
}

@media screen and (min-width: 600px) { 
  .helpbox__description { 
    margin-left: 10%;
    margin-right: 10%;
  }
}

</style>
